services:

  postgres:
    image: pgvector/pgvector:pg17
    env_file:
      - .env
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_DB: ${DATABASE_DB}
    ports:
      - "${DATABASE_PORT}:5432"
    volumes:
      - ./docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    networks:
      - backend

  app:
    build: .
    ports:
      - "${PORT}:3333"
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - HOST_URL=${HOST_URL}
      - API_KEY=${API_KEY}
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
    depends_on:
      - postgres
    networks:
      - backend

networks:
  backend:
    driver: bridge