# Variables
@baseUrl = http://localhost:3333

### Health
GET {{baseUrl}}/health

### Get rooms
# @name getRooms
GET {{baseUrl}}/rooms
Content-Type: application/json

### Create room
# @name createRoom
POST {{baseUrl}}/rooms
Content-Type: application/json

{
    "name": "Room 2",
    "description": "Room 2 description"
}

###

@roomId = {{createRoom.response.body.$.roomId}}

### Get Room Questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions
Content-Type: application/json

### Create Question
# @name getRoomQuestions
POST {{baseUrl}}/rooms/e06fd7f6-2090-4105-f0db-55807961e7b0/questions
Content-Type: application/json

{
    "question": "Quem sou eu?"
}