apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "helm.fullname" . }}
  namespace: default
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      {{- include "helm.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
     