apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: ai-api
  namespace: argocd

spec:
  project: default
  source:
    repoURL: git@github.com:RogerRG171/ai-backend.git
    targetRevision: HEAD
    path: helm
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-api-ns
  syncPolicy:
    syncOptions:
    - CreateNameSpace=true
    automated:
      selfHeal: true
      prune: true