name: CI Pipeline

on:
  push:
    branches:
     - main

permissions:
  contents: write

jobs:
  build-and-push:
    name: 'Build and Push'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate sha
        id: generate_sha
        run: |
          SHA=$(echo $GITHUB_SHA | head -c7)
          echo "sha=$SHA" >> $GITHUB_OUTPUT

      - name: Update Helm values.yaml with new tag
        run: |
          # Update the image tag in values.yaml
          sed -i "s/tag: \".*\"/tag: \"${{ steps.generate_sha.outputs.sha }}\"/" helm/values.yaml
          
          # Verify the change
          echo "Updated image tag to: ${{ steps.generate_sha.outputs.sha }}"
          grep "tag:" helm/values.yaml

      - name: Build docker image
        run: docker build -t roger171/api.ai.backend:${{ steps.generate_sha.outputs.sha }} .
        
      - name: Login into the container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: |
          docker push roger171/api.ai.backend:${{ steps.generate_sha.outputs.sha }}
          docker tag roger171/api.ai.backend:${{ steps.generate_sha.outputs.sha }} roger171/api.ai.backend:latest
          docker push roger171/api.ai.backend:latest

      - name: Commit and push updated values.yaml
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add helm/values.yaml
          git diff --staged --quiet || git commit -m "Update image tag to ${{ steps.generate_sha.outputs.sha }} [skip ci]"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git